/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NNUEBridge */

#ifndef _Included_NNUEBridge
#define _Included_NNUEBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NNUEBridge
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_NNUEBridge_init
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     NNUEBridge
 * Method:    eval
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NNUEBridge_eval
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
